#!/usr/bin/env python3
"""
Main runner for Kelly's Health Correlations Agent.
"""

import sys
import argparse
from datetime import datetime, timedelta
from data_collector import HealthDataCollector
from analytics import HealthAnalytics
from config import HealthConfig

class HealthAgent:
    """Main health correlations agent."""
    
    def __init__(self):
        self.collector = HealthDataCollector()
        self.analytics = HealthAnalytics()
    
    def daily_brief(self, save_to_vault: bool = True) -> str:
        """Generate daily health brief with insights."""
        print("🏃‍♀️ **Health Agent** - Daily Brief")
        print("=" * 40)
        
        # Get today's data
        yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        today_data = self.collector.collect_daily_data()
        
        brief_lines = []
        
        # Oura summary
        oura = today_data.get("oura")
        if oura:
            sleep = oura.get("sleep", {})
            readiness = oura.get("readiness", {})
            
            sleep_score = sleep.get("score", 0)
            readiness_score = readiness.get("score", 0)
            hrv = readiness.get("hrv_balance", 0)
            
            brief_lines.append(f"💍 **Oura:** Sleep {sleep_score}, Readiness {readiness_score}, HRV {hrv}")
            
            # Sleep categorization
            sleep_hours = 6 + (sleep_score / 100) * 3  # Rough estimate
            sleep_category = HealthConfig.categorize_sleep_hours(sleep_hours)
            readiness_category = HealthConfig.categorize_readiness(readiness_score)
            
            brief_lines.append(f"📊 **Status:** {sleep_category.title()} sleep (~{sleep_hours:.1f}h), {readiness_category} readiness")
        
        # Recent insights
        insights = self.analytics.generate_insights(14)  # Last 2 weeks
        if insights:
            brief_lines.append("")
            brief_lines.append("💡 **Recent Insights:**")
            for insight in insights[:2]:  # Top 2 insights
                brief_lines.append(f"  • {insight['message']}")
        
        # Performance prediction
        if oura:
            prediction = self._predict_performance(readiness_score, hrv, sleep_score)
            brief_lines.append("")
            brief_lines.append(f"🎯 **Performance Prediction:** {prediction}")
        
        brief_text = "\\n".join(brief_lines)
        print(brief_text)
        
        # Save to vault
        if save_to_vault:
            self._save_daily_brief_to_vault(brief_text, oura)
        
        return brief_text
    
    def _predict_performance(self, readiness: int, hrv: int, sleep_score: int) -> str:
        """Predict today's running performance based on recovery metrics."""
        # Simple rule-based prediction (can be enhanced with ML later)
        
        if readiness >= 80 and hrv >= 70:
            return "Excellent condition - target pace or faster expected"
        elif readiness >= 70 and hrv >= 60:
            return "Good condition - normal training pace expected"
        elif readiness >= 60 or hrv >= 50:
            return "Moderate condition - consider easier pace (+15-30 sec)"
        else:
            return "Poor condition - consider rest day or very easy effort"
    
    def _save_daily_brief_to_vault(self, brief_text: str, oura_data: dict):
        """Save daily brief to Kelly's Obsidian vault."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        vault_filename = f"{date_str}-health-brief.md"
        vault_path = HealthConfig.get_vault_path("daily", vault_filename)
        
        # Create Obsidian-friendly markdown
        date_title = datetime.now().strftime("%B %d, %Y")
        formatted_brief = brief_text.replace('\n', '\n')
        
        markdown_content = f"""# Health Brief - {date_title}

## Summary
{formatted_brief}

## Raw Data
"""
        
        if oura_data:
            sleep = oura_data.get("sleep", {})
            readiness = oura_data.get("readiness", {})
            
            markdown_content += f"""
### Oura Ring Data
- **Sleep Score:** {sleep.get('score', 'N/A')}
- **Readiness Score:** {readiness.get('score', 'N/A')}
- **HRV Balance:** {readiness.get('hrv_balance', 'N/A')}
- **Resting HR:** {readiness.get('resting_heart_rate', 'N/A')}
- **Temperature Deviation:** {readiness.get('temperature_deviation', 'N/A')}°

### Sleep Breakdown
- **Deep Sleep:** {sleep.get('deep_sleep', 'N/A')}%
- **REM Sleep:** {sleep.get('rem_sleep', 'N/A')}%
- **Efficiency:** {sleep.get('efficiency', 'N/A')}%
- **Restfulness:** {sleep.get('restfulness', 'N/A')}%
"""

        markdown_content += f"""

---
*Generated by Health Correlations Agent*  
*Date: {datetime.now().isoformat()}*

#health #daily-brief #oura #performance
"""
        
        try:
            with open(vault_path, 'w') as f:
                f.write(markdown_content)
            print(f"💾 Saved daily brief to vault: {vault_filename}")
        except Exception as e:
            print(f"⚠️ Failed to save to vault: {e}")
    
    def weekly_report(self) -> str:
        """Generate weekly performance and correlation report."""
        print("📈 **Health Agent** - Weekly Report")
        print("=" * 40)
        
        insights = self.analytics.generate_insights(7)  # Last week
        
        report_lines = [
            f"**Week of {(datetime.now() - timedelta(days=7)).strftime('%B %d, %Y')}**",
            ""
        ]
        
        for insight in insights:
            insight_type = insight.get("type", "unknown")
            
            if insight_type == "sleep_pace_correlation":
                correlation = insight.get("correlation", 0)
                strength = insight.get("strength", "weak")
                report_lines.append(f"🛌 **Sleep-Pace Correlation:** {strength.title()} correlation (r={correlation:.2f})")
                
            elif insight_type == "readiness_performance":
                data = insight.get("data", {})
                if data.get("avg_pace_excellent") and data.get("avg_pace_poor"):
                    pace_diff = data["avg_pace_poor"] - data["avg_pace_excellent"]
                    report_lines.append(f"⚡ **Readiness Impact:** {pace_diff:.1f} min/mi difference between excellent vs poor readiness")
                    
            elif insight_type == "optimal_conditions":
                conditions = insight.get("conditions", {})
                report_lines.append(f"🏆 **Optimal Conditions:** {conditions.get('avg_sleep_score', 0):.0f} sleep score, {conditions.get('avg_readiness_score', 0):.0f} readiness")
                
            elif insight_type == "hrv_alerts":
                drops = insight.get("drops", [])
                if drops:
                    recent_drop = drops[-1]
                    report_lines.append(f"⚠️ **HRV Alert:** {recent_drop['drop_percent']:.0f}% drop on {recent_drop['date']}")
        
        if len(insights) == 0:
            report_lines.append("📊 Insufficient data for correlations (need 7+ data points)")
        
        report_text = "\\n".join(report_lines)
        print(report_text)
        return report_text
    
    def recommend_workout(self) -> str:
        """Generate workout recommendation based on current recovery state."""
        print("🎯 **Health Agent** - Workout Recommendation")
        print("=" * 40)
        
        # Get latest Oura data
        oura_data = self.collector.collect_oura_data()
        
        if not oura_data:
            return "No recent Oura data available for recommendation"
        
        readiness = oura_data.get("readiness", {}).get("score", 0)
        hrv = oura_data.get("readiness", {}).get("hrv_balance", 0)
        sleep_score = oura_data.get("sleep", {}).get("score", 0)
        
        # Get historical context
        insights = self.analytics.generate_insights(21)  # 3 weeks context
        
        recommendation_lines = [
            f"📊 **Current State:** Readiness {readiness}, HRV {hrv}, Sleep {sleep_score}",
            ""
        ]
        
        # Base recommendation on current metrics
        if readiness >= 85 and hrv >= 75:
            recommendation_lines.append("✅ **Recommendation:** Go for it! Great conditions for quality work")
            recommendation_lines.append("🎯 **Target:** Normal pace or tempo work if planned")
            
        elif readiness >= 70 and hrv >= 60:
            recommendation_lines.append("👍 **Recommendation:** Good for normal training")
            recommendation_lines.append("🎯 **Target:** Easy to moderate pace as planned")
            
        elif readiness >= 55 or hrv >= 45:
            recommendation_lines.append("⚠️ **Recommendation:** Take it easy today")
            recommendation_lines.append("🎯 **Target:** Easy pace only (+30-45 seconds)")
            
        else:
            recommendation_lines.append("🛑 **Recommendation:** Consider rest or active recovery")
            recommendation_lines.append("🚶 **Alternative:** Walk, yoga, or very easy movement")
        
        # Add historical context if available
        for insight in insights:
            if insight.get("type") == "optimal_conditions":
                conditions = insight.get("conditions", {})
                optimal_readiness = conditions.get("avg_readiness_score", 0)
                recommendation_lines.append("")
                recommendation_lines.append(f"📈 **Context:** Your best runs average {optimal_readiness:.0f} readiness")
        
        recommendation_text = "\\n".join(recommendation_lines)
        print(recommendation_text)
        return recommendation_text
    
    def update_data(self, days: int = 7):
        """Update historical data."""
        print(f"🔄 Updating health data for last {days} days...")
        self.collector.update_recent_data(days)
        print("✅ Data update complete")
    
    def correlate(self, metric1: str, metric2: str):
        """Analyze specific correlation between two metrics."""
        print(f"🔍 Analyzing correlation: {metric1} vs {metric2}")
        
        # This is a simplified version - could be expanded for specific metric pairs
        insights = self.analytics.generate_insights(30)
        
        relevant_insights = [i for i in insights if metric1 in i.get("message", "").lower() or metric2 in i.get("message", "").lower()]
        
        if relevant_insights:
            for insight in relevant_insights:
                print(f"📊 {insight['message']}")
        else:
            print(f"❌ No correlation data found for {metric1} vs {metric2}")

def main():
    """Main CLI interface."""
    parser = argparse.ArgumentParser(description="Kelly's Health Correlations Agent")
    parser.add_argument("command", choices=[
        "brief", "report", "recommend", "update", "correlate"
    ], help="Command to execute")
    parser.add_argument("--days", type=int, default=7, help="Days of data for update")
    parser.add_argument("--metric1", help="First metric for correlation")
    parser.add_argument("--metric2", help="Second metric for correlation")
    
    args = parser.parse_args()
    
    agent = HealthAgent()
    
    try:
        if args.command == "brief":
            agent.daily_brief()
        elif args.command == "report":
            agent.weekly_report()
        elif args.command == "recommend":
            agent.recommend_workout()
        elif args.command == "update":
            agent.update_data(args.days)
        elif args.command == "correlate":
            if not args.metric1 or not args.metric2:
                print("Error: --metric1 and --metric2 required for correlate command")
                sys.exit(1)
            agent.correlate(args.metric1, args.metric2)
            
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()