#!/usr/bin/env python3
"""
Vault integration for Health Correlations Agent.
Provides easy access to health insights for main chat sessions.
"""

import os
import json
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from config import HealthConfig

class HealthVaultIntegration:
    """Helper class for accessing health insights from main sessions."""
    
    def __init__(self):
        HealthConfig.ensure_vault_paths()
    
    def get_latest_brief(self) -> Optional[str]:
        """Get the most recent daily health brief."""
        daily_path = HealthConfig.get_vault_path("daily")
        
        try:
            files = [f for f in os.listdir(daily_path) if f.endswith("-health-brief.md")]
            if not files:
                return None
                
            # Get most recent file
            latest_file = max(files)
            file_path = os.path.join(daily_path, latest_file)
            
            with open(file_path, 'r') as f:
                content = f.read()
            
            # Extract just the summary section
            lines = content.split('\n')
            summary_lines = []
            in_summary = False
            
            for line in lines:
                if line.startswith("## Summary"):
                    in_summary = True
                    continue
                elif line.startswith("## ") and in_summary:
                    break
                elif in_summary and line.strip():
                    summary_lines.append(line)
            
            return '\n'.join(summary_lines).strip()
            
        except Exception as e:
            print(f"Error reading latest brief: {e}")
            return None
    
    def get_recent_insights(self, days: int = 7) -> List[Dict]:
        """Get recent health insights and correlations."""
        from analytics import HealthAnalytics
        
        analytics = HealthAnalytics()
        insights = analytics.generate_insights(days)
        
        # Save insights to vault for reference
        self._save_insights_to_vault(insights)
        
        return insights
    
    def _save_insights_to_vault(self, insights: List[Dict]):
        """Save insights to vault in markdown format."""
        if not insights:
            return
            
        date_str = datetime.now().strftime("%Y-%m-%d")
        vault_filename = f"{date_str}-insights.md"
        vault_path = HealthConfig.get_vault_path("insights", vault_filename)
        
        markdown_content = f"""# Health Insights - {datetime.now().strftime("%B %d, %Y")}

"""
        
        for insight in insights:
            insight_type = insight.get("type", "unknown")
            message = insight.get("message", "")
            
            if insight_type == "sleep_pace_correlation":
                correlation = insight.get("correlation", 0)
                direction = insight.get("direction", "unknown")
                strength = insight.get("strength", "unknown")
                
                markdown_content += f"""## Sleep-Pace Correlation
- **Correlation:** {direction} ({correlation:.3f})
- **Strength:** {strength}
- **Finding:** {message}

"""
            elif insight_type == "readiness_performance":
                data = insight.get("data", {})
                markdown_content += f"""## Readiness vs Performance
- **Data Points:** {data.get('data_points', 0)} runs analyzed
- **Correlation:** {data.get('correlation', 0):.3f}
- **Average Paces by Readiness:**
  - Excellent (85+): {data.get('avg_pace_excellent', 'N/A')} min/mi
  - Good (70-85): {data.get('avg_pace_good', 'N/A')} min/mi
  - Fair (55-70): {data.get('avg_pace_fair', 'N/A')} min/mi
  - Poor (<55): {data.get('avg_pace_poor', 'N/A')} min/mi

"""
            elif insight_type == "optimal_conditions":
                conditions = insight.get("conditions", {})
                markdown_content += f"""## Optimal Performance Conditions
- **Sample Size:** {conditions.get('sample_size', 0)} best runs
- **Average Pace:** {conditions.get('avg_pace', 0):.1f} min/mi
- **Average Sleep Score:** {conditions.get('avg_sleep_score', 0):.0f}
- **Average Readiness:** {conditions.get('avg_readiness_score', 0):.0f}
- **Average HRV:** {conditions.get('avg_hrv_balance', 0):.0f}

"""
            elif insight_type == "hrv_alerts":
                drops = insight.get("drops", [])
                markdown_content += f"""## HRV Alerts
Recent significant drops detected:
"""
                for drop in drops[-3:]:  # Last 3 drops
                    markdown_content += f"- **{drop['date']}:** {drop['drop_percent']:.0f}% drop to {drop['value']}\n"
                
                markdown_content += "\n"
        
        markdown_content += f"""
---
*Generated by Health Correlations Agent*  
*Date: {datetime.now().isoformat()}*

#health #insights #correlations #analytics
"""
        
        try:
            with open(vault_path, 'w') as f:
                f.write(markdown_content)
            print(f"💾 Saved insights to vault: {vault_filename}")
        except Exception as e:
            print(f"⚠️ Failed to save insights to vault: {e}")
    
    def get_performance_context(self, current_readiness: int, current_hrv: int) -> str:
        """Get performance context based on recent patterns."""
        insights = self.get_recent_insights(14)  # Last 2 weeks
        
        context_lines = []
        
        for insight in insights:
            if insight.get("type") == "readiness_performance":
                data = insight.get("data", {})
                
                # Find which readiness band user is in
                if current_readiness >= 85:
                    expected_pace = data.get("avg_pace_excellent")
                    band = "excellent"
                elif current_readiness >= 70:
                    expected_pace = data.get("avg_pace_good")
                    band = "good"
                elif current_readiness >= 55:
                    expected_pace = data.get("avg_pace_fair")
                    band = "fair"
                else:
                    expected_pace = data.get("avg_pace_poor")
                    band = "poor"
                
                if expected_pace:
                    context_lines.append(f"With {band} readiness ({current_readiness}), your recent average pace is {expected_pace:.1f} min/mi")
            
            elif insight.get("type") == "optimal_conditions":
                conditions = insight.get("conditions", {})
                optimal_readiness = conditions.get("avg_readiness_score", 0)
                optimal_pace = conditions.get("avg_pace", 0)
                
                readiness_diff = current_readiness - optimal_readiness
                if abs(readiness_diff) < 5:
                    context_lines.append(f"You're in your optimal readiness range (avg {optimal_readiness:.0f} for best runs)")
                elif readiness_diff < -10:
                    context_lines.append(f"Readiness is {abs(readiness_diff):.0f} points below your optimal range ({optimal_readiness:.0f})")
        
        return "; ".join(context_lines) if context_lines else "Insufficient historical data for context"

def get_health_summary() -> str:
    """Quick function for main sessions to get health context."""
    integration = HealthVaultIntegration()
    
    # Get latest brief
    latest_brief = integration.get_latest_brief()
    if latest_brief:
        return f"**Latest Health Brief:**\n{latest_brief}"
    else:
        return "No recent health brief available"

def get_performance_prediction(readiness: int = None, hrv: int = None) -> str:
    """Quick performance prediction for main sessions."""
    if not readiness or not hrv:
        return "Need current readiness and HRV for prediction"
    
    integration = HealthVaultIntegration()
    context = integration.get_performance_context(readiness, hrv)
    
    # Simple prediction logic
    if readiness >= 85 and hrv >= 75:
        prediction = "Excellent condition - go for quality work"
    elif readiness >= 70 and hrv >= 60:
        prediction = "Good condition - normal training pace"
    elif readiness >= 55:
        prediction = "Moderate condition - take it easier"
    else:
        prediction = "Poor condition - consider rest day"
    
    return f"{prediction}. {context}"

if __name__ == "__main__":
    # Test the integration
    integration = HealthVaultIntegration()
    
    print("Testing vault integration...")
    
    # Test latest brief
    brief = integration.get_latest_brief()
    print(f"Latest brief: {brief}")
    
    # Test insights
    insights = integration.get_recent_insights(7)
    print(f"Found {len(insights)} recent insights")
    
    # Test context
    context = integration.get_performance_context(73, 66)
    print(f"Performance context: {context}")